baseURL = "https://hongweiqin.github.io/blog"
title = "Hongwei Qin's Blog"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
#disqusShortname = "" # Enable Disqus comments by entering your Disqus shortname
#googleAnalytics = "" # Enable Google Analytics by entering your tracking id
hasCJKLanguage = "true"

[Author] # Used in authorbox
  name = "Hongwei Qin"
  bio = "Ofcourse, I am the only author of my personal blog."
  avatar = "img/avatar.png"

[Params]
  subtitle = "Hongwei Qin's personal blog" # Deprecated in favor of .Site.Params.logo.subtitle
  description = "Hongwei Qin's Personal blog about everything" # Site description. Used in meta description
  copyright = "Hongwei Qin" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
#  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
#  authorbox = true # Show authorbox at bottom of pages if true
# toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
#  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
#  dateformat = "2006-01-02" # Change the format of dates
#  mathjax = true # Enable MathJax
#  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify # MathJax path
#  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
#  highlightColor = "#e22d30" # Override highlight color
#  customCSS = ["css/custom.css"] # Include custom CSS files
#  customJS = ["js/custom.js"] # Include custom JS files

[Params.logo]
  image = "placeholderrr.png" # Logo image. Path relative to "static"
  title = "Hongwei Qin's Blog" # Logo title, otherwise will use site title
  #subtitle = "Just another site" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[[Params.widgets.social.custom]]
  title = "My Home Page"
  url = "https://HongweiQin.github.io"

[Params.widgets.social]
  # Enable parts of social widget
#  facebook = "username"
#  twitter = "username"
#  instagram = "username"
#  linkedin = "username"
#  telegram = "username"
  github = "hongweiqin"
#  gitlab = "username"
#  bitbucket = "username"
  email = "glqhw@qq.com"

# Custom social links
#[[Params.widgets.social.custom]]
#  title = "Youtube"
#  url = "https://youtube.com/user/username"
#  icon = "youtube.svg" # Optional. Path relative to "layouts/partials"

